/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILending } from "./ILending";
export type { Lending } from "./Lending";
export type { LendingContract } from "./LendingContract";
