/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Math",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Math__factory>;
    getContractFactory(
      name: "ILending",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILending__factory>;
    getContractFactory(
      name: "Lending",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Lending__factory>;
    getContractFactory(
      name: "LendingContract",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LendingContract__factory>;

    getContractAt(
      name: "Math",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Math>;
    getContractAt(
      name: "ILending",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ILending>;
    getContractAt(
      name: "Lending",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Lending>;
    getContractAt(
      name: "LendingContract",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LendingContract>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
